name: Build app on dev Push

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'node' # uses the latest stable version

      - name: Install dependencies
        run: npm install

      - name: Start server and check for errors
        run: |
          # Start server in background and redirect output
          npm run server &> server.log &
          SERVER_PID=$!

          # Wait a few seconds to let server start
          sleep 5

          # Check if server process is still running (means it didn't crash immediately)
          if ps -p $SERVER_PID > /dev/null; then
            echo "Server started successfully."
            # Kill the server to clean up
            kill $SERVER_PID
          else
            echo "Server failed to start. Here are the logs:"
            cat server.log
            exit 1
          fi



          
            # - name: Build the app
            #   run: npm run build
